name: Trigger documents sync

on:
  push:
    branches: [ master ]
    paths:
      - .github/workflows/docs-sync.yml
      - documents
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger sync workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.repository_owner }}/eunomia.dev
          event-type: trigger-document-sync

